name: Terraform
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        id: install

     



